---
title: "ESM 204 Hw 4"
author: "Taylor Medina, Matt McCafferty"
date: '2022-05-16'
output: html_document
---

```{r setup, include = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(patchwork)
```

```{r}
damages <- read_csv(here('data/damages.csv'))
warming <- read_csv(here('data/warming.csv'))
```

## 1

```{r}
# create quadratic model
damages$warming2 <- damages$warming ^ 2
damages.qm <- lm(damages ~ 0 + warming + warming2, data = damages)

warming_seq <- seq(0, max(damages$warming), by = 0.01)
fit <- predict(damages.qm, list(warming = warming_seq, warming2 = warming_seq ^ 2)) %>% 
  cbind(warming_seq) %>% 
  as.data.frame()

ggplot() +
  geom_point(data = damages, aes(x = warming, y = damages), color = 'grey') +
  geom_line(data = fit, aes(x = warming_seq, y = .), color = 'red') +
  labs(x = expression('warming (°C)'),
       y = 'Total climate damage ($)') +
  theme_minimal()
```

**Figure 1:** Fitted quadratic regression model to environmental damages from warming.

The quadratic regression model modeling environmental damages as a function of global warming is given as:

$$ \hat D = 1.941 \times 10^{13} T ^ 2 - 1.060 \times 10^{12} T $$

## 2

```{r}
warming_predict <- warming %>% 
  mutate(damage_np = predict(damages.qm, list(warming = warming_baseline, warming2 = warming_baseline^2)), # damage without pulse
         damage_wp = predict(damages.qm, list(warming = warming_pulse, warming2 = warming_pulse^2)), # damage with pulse
         damages_diff = damage_wp - damage_np, # differences in damage
         new_difference_norm = (damage_wp / 35e9) - (damage_np / 35e9),
         norm_damage_wp = damage_wp / 35e9) # normalized difference

p1 <- ggplot(warming_predict) +
  geom_line(aes(x = year, y = damage_np)) +
  theme_minimal()

p2 <- ggplot(warming_predict) +
  geom_line(aes(x = year, y = damage_wp)) +
  theme_minimal()

p3 <- ggplot(warming_predict) +
  geom_line(aes(x = year, y = damages_diff)) +
  theme_minimal()

p4 <- ggplot(warming_predict) +
  geom_line(aes(x = year, y = new_difference_norm)) +
  theme_minimal()

(p1 | p2) / (p3 | p4)



```

## 3

```{r}
# function to calculate present value based off of one r
pv <- function(data, r){
  
  pv.df <- data.frame()
  
  for (i in 1:79){
  
     pv <- data[i] / (1 + r) ^ i
     pv.df <- rbind(pv.df, pv)
     col_sum <- colSums(pv.df)
     
  }
  
  return(col_sum)
  
}

# function creates a dataframe for multiple r values
by_r <- function(data, r){
  
  df <- data.frame()
  
  for(i in 1:length(r)){
    pv_r <- pv(data, r[i])
    df <- rbind(df, pv_r)
  }
  
  final.df <- cbind(r, df)
  
  return(final.df)
}

rseq <- seq(0.002, 0.003, by = 0.00001) 
r.df <- by_r(warming_predict$norm_damage_wp, rseq)
```


## 4
r = ρ + ηg
r = 0.001 + 2(0.01)= 2.1%

